-- ANÁLISE PRO — analytics independente para múltiplas páginas de vendas
-- Aplicar no Supabase antes de usar o painel/tracker.

create extension if not exists pgcrypto;

create table if not exists public.analytics_pro_sites (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  domain text,
  site_key text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_pro_sessions (
  id text primary key,
  site_id uuid not null references public.analytics_pro_sites(id) on delete cascade,
  visitor_id text not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  entry_url text,
  entry_path text,
  landing_referrer text,
  source text,
  medium text,
  campaign text,
  term text,
  content text,
  click_id text,
  device_type text,
  browser text,
  os text,
  language text,
  timezone text,
  screen_width integer,
  screen_height integer,
  viewport_width integer,
  viewport_height integer,
  network_type text,
  pageviews integer not null default 0,
  max_scroll integer not null default 0,
  engaged_seconds integer not null default 0,
  converted boolean not null default false,
  conversion_value numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_pro_events (
  id bigint generated by default as identity primary key,
  site_id uuid not null references public.analytics_pro_sites(id) on delete cascade,
  session_id text not null references public.analytics_pro_sessions(id) on delete cascade,
  visitor_id text not null,
  event_name text not null,
  page_url text,
  page_path text,
  page_title text,
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_pro_utm_links (
  id uuid primary key default gen_random_uuid(),
  site_id uuid not null references public.analytics_pro_sites(id) on delete cascade,
  name text not null,
  destination_url text not null,
  source text not null,
  medium text not null,
  campaign text not null,
  term text,
  content text,
  generated_url text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_ap_sessions_site_time on public.analytics_pro_sessions(site_id, first_seen_at desc);
create index if not exists idx_ap_sessions_site_campaign on public.analytics_pro_sessions(site_id, campaign, first_seen_at desc);
create index if not exists idx_ap_sessions_site_visitor on public.analytics_pro_sessions(site_id, visitor_id, first_seen_at desc);
create index if not exists idx_ap_sessions_site_converted on public.analytics_pro_sessions(site_id, converted, first_seen_at desc);
create index if not exists idx_ap_events_site_time on public.analytics_pro_events(site_id, created_at desc);
create index if not exists idx_ap_events_site_name on public.analytics_pro_events(site_id, event_name, created_at desc);
create index if not exists idx_ap_events_session on public.analytics_pro_events(session_id, created_at);
create index if not exists idx_ap_utm_links_site on public.analytics_pro_utm_links(site_id, created_at desc);

alter table public.analytics_pro_sites enable row level security;
alter table public.analytics_pro_sessions enable row level security;
alter table public.analytics_pro_events enable row level security;
alter table public.analytics_pro_utm_links enable row level security;

drop policy if exists "ap sites admin read" on public.analytics_pro_sites;
create policy "ap sites admin read" on public.analytics_pro_sites
for select to authenticated
using (owner_id = auth.uid() or public.has_role(auth.uid(), 'store_admin'));

drop policy if exists "ap sites admin insert" on public.analytics_pro_sites;
create policy "ap sites admin insert" on public.analytics_pro_sites
for insert to authenticated
with check (owner_id = auth.uid() or public.has_role(auth.uid(), 'store_admin'));

drop policy if exists "ap sites admin update" on public.analytics_pro_sites;
create policy "ap sites admin update" on public.analytics_pro_sites
for update to authenticated
using (owner_id = auth.uid() or public.has_role(auth.uid(), 'store_admin'))
with check (owner_id = auth.uid() or public.has_role(auth.uid(), 'store_admin'));

drop policy if exists "ap sessions admin read" on public.analytics_pro_sessions;
create policy "ap sessions admin read" on public.analytics_pro_sessions
for select to authenticated
using (exists (select 1 from public.analytics_pro_sites s where s.id = site_id and (s.owner_id = auth.uid() or public.has_role(auth.uid(), 'store_admin'))));

drop policy if exists "ap events admin read" on public.analytics_pro_events;
create policy "ap events admin read" on public.analytics_pro_events
for select to authenticated
using (exists (select 1 from public.analytics_pro_sites s where s.id = site_id and (s.owner_id = auth.uid() or public.has_role(auth.uid(), 'store_admin'))));

drop policy if exists "ap utm admin all" on public.analytics_pro_utm_links;
create policy "ap utm admin all" on public.analytics_pro_utm_links
for all to authenticated
using (exists (select 1 from public.analytics_pro_sites s where s.id = site_id and (s.owner_id = auth.uid() or public.has_role(auth.uid(), 'store_admin'))))
with check (exists (select 1 from public.analytics_pro_sites s where s.id = site_id and (s.owner_id = auth.uid() or public.has_role(auth.uid(), 'store_admin'))));

grant select, insert, update on public.analytics_pro_sites to authenticated;
grant select on public.analytics_pro_sessions, public.analytics_pro_events to authenticated;
grant select, insert, update, delete on public.analytics_pro_utm_links to authenticated;
grant all on public.analytics_pro_sites, public.analytics_pro_sessions, public.analytics_pro_events, public.analytics_pro_utm_links to service_role;
grant usage, select on all sequences in schema public to service_role;

-- RPC usada pelo tracker público. A função valida o site_key e nunca expõe a service role.
create or replace function public.analytics_pro_collect(
  p_site_key text,
  p_session_id text,
  p_visitor_id text,
  p_event_name text,
  p_page_url text default null,
  p_page_path text default null,
  p_page_title text default null,
  p_event_data jsonb default '{}'::jsonb,
  p_utm jsonb default '{}'::jsonb,
  p_device jsonb default '{}'::jsonb,
  p_at timestamptz default now()
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_site_id uuid;
  v_existing_id text;
  v_event_id bigint;
  v_scroll integer := 0;
  v_engaged integer := 0;
  v_pageview boolean := false;
  v_converted boolean := false;
  v_value numeric(12,2) := 0;
begin
  if length(coalesce(p_site_key, '')) < 12 or length(coalesce(p_session_id, '')) < 8 or length(coalesce(p_visitor_id, '')) < 8 then
    return jsonb_build_object('ok', false, 'reason', 'invalid_identity');
  end if;

  select id into v_site_id from public.analytics_pro_sites where site_key = p_site_key and active = true limit 1;
  if v_site_id is null then
    return jsonb_build_object('ok', false, 'reason', 'invalid_site');
  end if;

  v_scroll := greatest(0, least(100, coalesce((p_event_data->>'scroll_percent')::integer, 0)));
  v_engaged := greatest(0, coalesce((p_event_data->>'engaged_seconds')::integer, 0));
  v_pageview := p_event_name = 'page_view';
  v_converted := p_event_name in ('purchase', 'conversion', 'lead') or coalesce((p_event_data->>'converted')::boolean, false);
  v_value := coalesce(nullif(p_event_data->>'value', '')::numeric, 0);

  select id into v_existing_id
  from public.analytics_pro_sessions
  where id = p_session_id and site_id = v_site_id
  limit 1;

  if v_existing_id is null then
    insert into public.analytics_pro_sessions (
      id, site_id, visitor_id, first_seen_at, last_seen_at, entry_url, entry_path,
      landing_referrer, source, medium, campaign, term, content, click_id,
      device_type, browser, os, language, timezone, screen_width, screen_height,
      viewport_width, viewport_height, network_type, pageviews, max_scroll,
      engaged_seconds, converted, conversion_value
    ) values (
      p_session_id, v_site_id, p_visitor_id, p_at, p_at, p_page_url, p_page_path,
      nullif(p_event_data->>'referrer', ''),
      nullif(p_utm->>'source', ''), nullif(p_utm->>'medium', ''), nullif(p_utm->>'campaign', ''),
      nullif(p_utm->>'term', ''), nullif(p_utm->>'content', ''), nullif(p_utm->>'click_id', ''),
      nullif(p_device->>'device_type', ''), nullif(p_device->>'browser', ''), nullif(p_device->>'os', ''),
      nullif(p_device->>'language', ''), nullif(p_device->>'timezone', ''),
      nullif(p_device->>'screen_width', '')::integer, nullif(p_device->>'screen_height', '')::integer,
      nullif(p_device->>'viewport_width', '')::integer, nullif(p_device->>'viewport_height', '')::integer,
      nullif(p_device->>'network_type', ''), case when v_pageview then 1 else 0 end,
      v_scroll, v_engaged, v_converted, v_value
    );
  else
    update public.analytics_pro_sessions
    set last_seen_at = greatest(last_seen_at, p_at),
        pageviews = pageviews + case when v_pageview then 1 else 0 end,
        max_scroll = greatest(max_scroll, v_scroll),
        engaged_seconds = greatest(engaged_seconds, v_engaged),
        converted = converted or v_converted,
        conversion_value = case when v_value > 0 then v_value else conversion_value end
    where id = p_session_id and site_id = v_site_id;
  end if;

  insert into public.analytics_pro_events (site_id, session_id, visitor_id, event_name, page_url, page_path, page_title, event_data, created_at)
  values (v_site_id, p_session_id, p_visitor_id, left(coalesce(p_event_name, 'unknown'), 80), p_page_url, p_page_path, p_page_title, coalesce(p_event_data, '{}'::jsonb), p_at)
  returning id into v_event_id;

  return jsonb_build_object('ok', true, 'event_id', v_event_id);
exception when others then
  return jsonb_build_object('ok', false, 'reason', 'collector_error');
end;
$$;

revoke all on function public.analytics_pro_collect(text,text,text,text,text,text,text,jsonb,jsonb,jsonb,timestamptz) from public;
grant execute on function public.analytics_pro_collect(text,text,text,text,text,text,text,jsonb,jsonb,jsonb,timestamptz) to anon, authenticated, service_role;

comment on table public.analytics_pro_sites is 'Análise Pro: páginas de vendas monitoradas.';
comment on table public.analytics_pro_sessions is 'Análise Pro: sessões agregadas por visitante/página.';
comment on table public.analytics_pro_events is 'Análise Pro: eventos detalhados de comportamento.';
comment on table public.analytics_pro_utm_links is 'Análise Pro: links UTM gerados para campanhas.';
