-- HOTBOX DELIVERY — Meta Pixel + Conversions API (rastreamento enriquecido)
-- Incremental e idempotente. Não apaga pedidos, produtos, clientes ou configurações.
-- Execute no Supabase SQL Editor antes do deploy dos arquivos desta atualização.

begin;

alter table public.store_config
  add column if not exists meta_pixel_enabled boolean not null default false,
  add column if not exists meta_pixel_script text,
  add column if not exists meta_pixel_on_menu boolean not null default true,
  add column if not exists meta_pixel_on_bio boolean not null default true,
  add column if not exists meta_pixel_id text,
  add column if not exists meta_capi_access_token text,
  add column if not exists meta_test_event_code text;

comment on column public.store_config.meta_pixel_script is
  'Código/ID do Meta Pixel configurado pelo administrador. O frontend extrai somente o Pixel ID.';
comment on column public.store_config.meta_capi_access_token is
  'Token secreto da Meta Conversions API. Nunca deve ser exposto em views/RPCs públicas.';

-- Auditoria server-side da CAPI.
create table if not exists public.meta_capi_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  phone text,
  payload jsonb not null default '{}'::jsonb,
  response jsonb,
  success boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.meta_capi_events
  add column if not exists event_id text,
  add column if not exists phone text,
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists response jsonb,
  add column if not exists success boolean not null default false,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists order_id uuid references public.orders(id) on delete set null,
  add column if not exists checkout_id uuid references public.site_checkout_sessions(id) on delete set null,
  add column if not exists source text;

create index if not exists idx_meta_capi_events_event_id
  on public.meta_capi_events(event_id)
  where event_id is not null;

create index if not exists idx_meta_capi_events_order
  on public.meta_capi_events(order_id)
  where order_id is not null;

create index if not exists idx_meta_capi_events_checkout
  on public.meta_capi_events(checkout_id)
  where checkout_id is not null;

create index if not exists idx_meta_capi_events_created
  on public.meta_capi_events(created_at desc);

-- Contexto opcional para checkouts server-side/webhooks futuros.
alter table public.site_checkout_sessions
  add column if not exists meta_tracking jsonb not null default '{}'::jsonb;

grant all on public.meta_capi_events to service_role;
grant usage, select on all sequences in schema public to service_role;

notify pgrst, 'reload schema';

commit;

-- Diagnóstico opcional:
-- select
--   meta_pixel_enabled,
--   meta_pixel_on_menu,
--   meta_pixel_on_bio,
--   meta_pixel_id,
--   case when coalesce(meta_capi_access_token,'')='' then 'SEM TOKEN CAPI' else 'TOKEN CAPI SALVO' end as capi
-- from public.store_config
-- where id=1;
