-- HOTBOX ANALYTICS 360 — jornada completa do cliente
create table if not exists public.analytics_sessions (
  id text primary key,
  visitor_id text not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  converted boolean not null default false,
  converted_at timestamptz,
  revenue numeric(12,2) not null default 0,
  entry_path text,
  landing_referrer text,
  source text,
  medium text,
  campaign text,
  term text,
  content text,
  click_id text,
  device_type text,
  browser text,
  os text,
  language text,
  timezone text,
  screen_width integer,
  screen_height integer,
  viewport_width integer,
  viewport_height integer,
  ip_address text,
  country text,
  region text,
  city text,
  user_agent text,
  customer_name text,
  customer_phone text,
  checkout_id text,
  order_id text,
  payment_method text,
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  session_id text not null references public.analytics_sessions(id) on delete cascade,
  visitor_id text not null,
  event_name text not null,
  event_category text not null default 'engagement',
  page_path text,
  page_title text,
  product_id text,
  product_name text,
  checkout_id text,
  order_id text,
  payment_method text,
  value numeric(12,2),
  quantity integer,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_analytics_sessions_first_seen on public.analytics_sessions(first_seen_at desc);
create index if not exists idx_analytics_sessions_last_seen on public.analytics_sessions(last_seen_at desc);
create index if not exists idx_analytics_sessions_source on public.analytics_sessions(source, medium);
create index if not exists idx_analytics_sessions_campaign on public.analytics_sessions(campaign);
create index if not exists idx_analytics_sessions_converted on public.analytics_sessions(converted, converted_at desc);
create index if not exists idx_analytics_sessions_visitor on public.analytics_sessions(visitor_id, first_seen_at desc);
create index if not exists idx_analytics_events_session on public.analytics_events(session_id, created_at);
create index if not exists idx_analytics_events_name on public.analytics_events(event_name, created_at desc);
create index if not exists idx_analytics_events_product on public.analytics_events(product_id, created_at desc);
create index if not exists idx_analytics_events_checkout on public.analytics_events(checkout_id) where checkout_id is not null;

alter table public.analytics_sessions enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists "store admin reads analytics sessions" on public.analytics_sessions;
create policy "store admin reads analytics sessions" on public.analytics_sessions
for select to authenticated using (public.has_role(auth.uid(), 'store_admin'));

drop policy if exists "store admin reads analytics events" on public.analytics_events;
create policy "store admin reads analytics events" on public.analytics_events
for select to authenticated using (public.has_role(auth.uid(), 'store_admin'));

grant select on public.analytics_sessions, public.analytics_events to authenticated;
grant all on public.analytics_sessions, public.analytics_events to service_role;

comment on table public.analytics_sessions is 'HOTBOX Analytics 360: uma linha por sessão de navegação do cliente.';
comment on table public.analytics_events is 'HOTBOX Analytics 360: eventos detalhados da jornada, sem armazenar senha/CVV/cartão.';
